services:
  vino:
    build:
      context: .
      dockerfile: Dockerfile
      target: final
    volumes:
      - ./:/app
      
  vino-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    